### ISSUE TITLE
Use ShellFileOperations to move the file to a location that requires admin rights will cause exception

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#151]
Example location C:\Windows

Use ShellFileOperations to move any file to here, UAC will pop out. Then you will get "Class not registered" exception.

**Comment by dahall** [comment]
I have just run the following test and was prompt three times for UAC access, but the unit test succeeded. Are you doing something different?
```cs
var tmp = new FileInfo(randomFilePath);
var winDir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
Assert.That(() => ShellFileOperations.Move(tmp.FullName, winDir, null, ShellFileOperations.OperationFlags.Silent), Throws.Nothing);
Assert.IsTrue(File.Exists(Path.Combine(winDir, Path.GetFileName(tmp.FullName))));
```

**Comment by zhuxb711** [comment]
like this:
```csharp
            try
            {
                if (!Directory.Exists(DestinationPath))
                {
                    _ = Directory.CreateDirectory(DestinationPath);
                }

                using (ShellFileOperations Operation = new ShellFileOperations
                {
                    Options = ShellFileOperations.OperationFlags.AddUndoRecord | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent
                })
                {
                    Operation.UpdateProgress += Progress;
                    Operation.PostMoveItem += PostMoveEvent;

                    foreach (KeyValuePair<string, string> SourceInfo in Source)
                    {
                        using (ShellItem SourceItem = new ShellItem(SourceInfo.Key))
                        using (ShellFolder DestItem = new ShellFolder(DestinationPath))
                        {
                            Operation.QueueMoveOperation(SourceItem, DestItem, null);
                        }
                    }

                    Operation.PerformOperations();

                    Operation.PostMoveItem -= PostMoveEvent;
                    Operation.UpdateProgress -= Progress;
                }

                return true;
            }
            catch
            {
                return false;
            }
```

**Comment by dahall** [comment]
I think the problem may be that you are disposing the `ShellItem` instances (`SourceItem` and `DestItem`) before `PerformOperations` has completed.

**Comment by dahall** [comment]
I'd propose:
```cs
try
{
   if (!Directory.Exists(DestinationPath))
   {
      _ = Directory.CreateDirectory(DestinationPath);
   }

   using (ShellFolder DestItem = new ShellFolder(DestinationPath))
   using (ShellFileOperations Operation = new ShellFileOperations
   {
      Options = ShellFileOperations.OperationFlags.AddUndoRecord | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent
   })
   {
      Operation.UpdateProgress += Progress;
      Operation.PostMoveItem += PostMoveEvent;

      List<ShellItem> sources = new List<string>(Source.Select(kv => new ShellItem(kv.Key))));
      Operation.QueueMoveOperation(SourceItem, DestItem, null);
      Operation.PerformOperations();
	  foreach (ShellItem item in sources)
	     item.Dispose();
	  sources.Clear();

      Operation.PostMoveItem -= PostMoveEvent;
      Operation.UpdateProgress -= Progress;
   }

   return true;
}
catch
{
   return false;
}
```

**Comment by zhuxb711** [comment]
But why there is no exception when I copy other files?

I disposed the ShellItem instances (SourceItem and DestItem) before PerformOperations complete.

If this way is wrong, then for files in other places, the same error should appear to prompt me not to dispose the ShellItem

**Comment by zhuxb711** [comment]
```csharp
foreach (ShellItem item in sources)
         item.Dispose();
```

This method does not feel very elegant, because in general, it is assumed that the object can be disposed as long as the object is passed into the function, so I think the best way is to copy these objects in QueueMoveOperation. Instead of relying on them not being disposed externally

**Comment by dahall** [comment]
> But why there is no exception when I copy other files?

I think it has to do with the transactional nature of `PerformOperations`. Nothing is really done with the `ShellItem` instances until that method is called. However, as I originally stated, this early disposal **may** be the cause of the problem. I haven't done any testing to confirm or refute that.
> so I think the best way is to copy these objects in QueueMoveOperation

I'm hesitant to do this because then I have to queue every operation/transaction by pulling the PIDL, copying, and then retaining it. In COM, this is a very typical pattern. And, even if you don't explicitly dispose the ShellItem instances, the garbage collector will once they all go out of scope.

**Comment by zhuxb711** [comment]
>#### even if you don't explicitly dispose the ShellItem instances, the garbage collector will once they all go out of scope
For objects in C#, it is difficult to say when the GC will reclaim them. Because the time when the GC calls the Finalize method is uncertain, so I don’t agree with you.

**Comment by dahall** [comment]
If you change your method to not dispose the ShellItem instances until after calling PerformOperations, do you still see the exception?

**Comment by zhuxb711** [comment]
The problem still exists. I got a COMException and the Message is “class is not registered”

StackTrace:
   at Vanara.PInvoke.Shell32.IFileOperation.PerformOperations()
   at Vanara.Windows.Shell.ShellFileOperations.PerformOperations()

**Comment by dahall** [comment]
I just ran the following code, which I think closely resembles yours, without error.
```cs
using var tmp = new TempFile();
var winDir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);

using ShellFileOperations Operation = new ShellFileOperations
{
   Options = ShellFileOperations.OperationFlags.AddUndoRecord | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent
};
Operation.UpdateProgress += Operation_UpdateProgress;
Operation.PostMoveItem += Operation_PostMoveItem;

using (var fld = new ShellFolder(winDir))
using (var item = new ShellItem(tmp.FullName))
   Assert.That(() => Operation.QueueMoveOperation(item, fld), Throws.Nothing);
Assert.That(() => Operation.PerformOperations(), Throws.Nothing);

Operation.PostMoveItem -= Operation_PostMoveItem;
Operation.UpdateProgress -= Operation_UpdateProgress;

static void Operation_PostMoveItem(object sender, ShellFileOperations.ShellFileOpEventArgs e) => Debug.WriteLine("Post move...");
static void Operation_UpdateProgress(object sender, System.ComponentModel.ProgressChangedEventArgs e) => Debug.WriteLine("Progress...");
```

I did find an [article ](https://stackoverflow.com/questions/1496214/how-to-solve-com-exception-class-not-registered-exception-from-hresult-0x80040) that suggests that that exception can occur when crossing X86 and X64 code. Could that be the cause in your system?

**Comment by dahall** [comment]
Ha! I found a way to reproduce the error: Make a call that throws an exception in the event handler. In my case, putting a call to e.DestItem.Name in the PostMoveItem event handler caused PerformOperations to throw the "Class not registered" exception. Once I corrected the event handler (by checking if e.DestItem was null first), the exception went away. Check your event handlers and let me know.

**Comment by zhuxb711** [comment]
[See here](https://github.com/zhuxb711/RX-Explorer/blob/cca1473fc9b60fd161f0a09a6b2da9118df09fe3/FullTrustProcess/Program.cs#L391)

No exception will be thrown in PostMoveItem, but it just failed...

**Comment by dahall** [comment]
Will you either remove the handlers or comment out all their code and tell me if the exception is still thrown?

**Comment by zhuxb711** [comment]
I have commented out all these codes in handlers, but it still throws an exception.

**Comment by dahall** [comment]
Have you found any way to reproduce this or work around this problem in a smaller code sample?

**Comment by zhuxb711** [comment]
No, I guess this has something to do with the permissions of the application, I will close this issue first.
