### ISSUE TITLE
Vanara.Windows.Shell throws COMException when enumerating special items (WinAppSDK 1.5)

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#474]
**Describe the bug and how to reproduce**

Using `Vanara.Windows.Shell` v4.0.2

Enumerating my `Desktop folder` <`ShellFolder`> using the code below. After getting resulting child Items `shFolder.EnumerateChildren(...)`, accesssing the children <`IEnumerable<ShellItem>`> throws COMExceptions for - in my case - nine items.

**What code is involved**

```
            using var shFolder = new ShellFolder(shItemId);
            var children = shFolder.EnumerateChildren(FolderItemFilter.NonFolders | FolderItemFilter.Folders);
            var shellItems = children as ShellItem[] ?? children.ToArray();
```

I can reproduce this behaviour with some special folders in the Shell32 Namespace, like `This PC` and others. Others work well.

**Expected behavior**

Getting the Items without `COMException`s.

**Screenshots**

Youtube (low quality): https://youtu.be/ijMJe8dk9w4?si=TKNZEdk25pzY5Nix

**Comment by tajbender** [comment]
As I can see, this is an internal exception when getting the array, which is _not_ handed through to the caller.

However, I was wondering if this is expected behavior?

**Comment by tajbender** [comment]
Here you can see, which folder fail in particularly:
```
12:26:28:930	.NativeTreeViewOnSelectionChanged() Desktop
12:26:28:930	.Navigate(`Desktop`)
12:26:28:930	.OnCurrentFolderBrowserItemChanged(<'Desktop'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:26:29:181	.ExtractChildItems <Desktop> extracting...
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:29:181	.ExtractChildItems <Desktop> extracted: 25 items.
12:26:32:676	.NativeTreeViewOnSelectionChanged() Libraries
12:26:32:676	.Navigate(`Libraries`)
12:26:32:676	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:26:32:676	.ExtractChildItems <Libraries> extracting...
12:26:32:676	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
12:26:32:924	.ExtractChildItems <Libraries> extracted: 6 items.
12:26:34:184	.NativeTreeViewOnSelectionChanged() This PC
12:26:34:184	.Navigate(`This PC`)
12:26:34:184	.OnCurrentFolderBrowserItemChanged(<'This PC'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:26:34:184	.ExtractChildItems <This PC> extracting...
12:26:34:184	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:34:184	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:34:184	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:34:184	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:34:184	.ExtractChildItems <This PC> extracted: 4 items.
12:26:35:933	.NativeTreeViewOnSelectionChanged() Recycle Bin
12:26:35:933	.Navigate(`Recycle Bin`)
12:26:35:933	.OnCurrentFolderBrowserItemChanged(<'Recycle Bin'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:26:35:933	.ExtractChildItems <Recycle Bin> extracting...
12:26:35:933	.ExtractChildItems <Recycle Bin> extracted: 0 items.
12:26:38:425	.NativeTreeViewOnSelectionChanged() Control Panel
12:26:38:425	.Navigate(`Control Panel`)
12:26:38:425	.OnCurrentFolderBrowserItemChanged(<'Control Panel'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:26:38:425	.ExtractChildItems <Control Panel> extracting...
12:26:38:425	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:425	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:425	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:425	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:425	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:675	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:675	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:675	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:675	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:26:38:675	.ExtractChildItems <Control Panel> extracted: 9 items.```

May I'm missing some privileges in the manifest?

Regards, tajbender

**Comment by tajbender** [comment]
btw., This is the source base we are talking about: https://github.com/tajbender/electrifier.v1.24/tree/509cf684fb93db24b809ad77fd77c4e2d91207b3

I also see, navigating to `Libraries` causes other exceptions when done multiple times.

```
19:32:32:430	.NativeTreeViewOnSelectionChanged() Libraries
19:32:32:430	.Navigate(`Libraries`)
19:32:32:430	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
19:32:32:676	.ExtractChildItems <Libraries> extracting...
19:32:32:676	.ExtractChildItems <Libraries> extracted: 6 items.
19:32:38:678	.NativeTreeViewOnSelectionChanged() Pictures
19:32:38:678	.Navigate(`Pictures`)
19:32:38:678	.OnCurrentFolderBrowserItemChanged(<'Pictures'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
19:32:38:678	.ExtractChildItems <Pictures> extracting...
19:32:38:929	.ExtractChildItems <Pictures> extracted: 36 items.
19:32:41:926	.NativeTreeViewOnSelectionChanged() Libraries
19:32:41:926	.Navigate(`Libraries`)
19:32:41:926	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
19:32:41:926	.ExtractChildItems <Libraries> extracting...
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
19:32:41:926	.ExtractChildItems <Libraries> extracted: 6 items.
```

- 1st time: No exception, but `DisplayName == null`
- 2nd time: `System.IO.FileLoadException`, but DisplasNames are available.

**Comment by tajbender** [comment]
> btw., This is the source base we are talking about: https://github.com/tajbender/electrifier.v1.24/tree/509cf684fb93db24b809ad77fd77c4e2d91207b3
> 
> I also see, navigating to `Libraries` causes other exceptions when done multiple times.
> 
> ```
> 19:32:32:430	.NativeTreeViewOnSelectionChanged() Libraries
> 19:32:32:430	.Navigate(`Libraries`)
> 19:32:32:430	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
> 19:32:32:676	.ExtractChildItems <Libraries> extracting...
> 19:32:32:676	.ExtractChildItems <Libraries> extracted: 6 items.
> 19:32:38:678	.NativeTreeViewOnSelectionChanged() Pictures
> 19:32:38:678	.Navigate(`Pictures`)
> 19:32:38:678	.OnCurrentFolderBrowserItemChanged(<'Pictures'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
> 19:32:38:678	.ExtractChildItems <Pictures> extracting...
> 19:32:38:929	.ExtractChildItems <Pictures> extracted: 36 items.
> 19:32:41:926	.NativeTreeViewOnSelectionChanged() Libraries
> 19:32:41:926	.Navigate(`Libraries`)
> 19:32:41:926	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
> 19:32:41:926	.ExtractChildItems <Libraries> extracting...
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	Exception thrown: 'System.IO.FileLoadException' in Vanara.Windows.Shell.Common.dll
> 19:32:41:926	.ExtractChildItems <Libraries> extracted: 6 items.
> ```
> 
> * 1st time: No exception, but `DisplayName == null`
> * 2nd time: `System.IO.FileLoadException`, but DisplasNames are available.

Sorry for that, I've found my bug: 

https://github.com/electrifier/electrifier-v1.24/pull/21/commits/fb6fa1baf27d7a6b554bb96fba0f1e5c22ab6045

Creating a new copy of `ShellItem = new (shItem.PIDL);` did it.

**Comment by tajbender** [comment]
Hmm, I guess *this is* an issue with privileges:

`17:33:27:943	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\System.Security.Permissions.dll'. Symbol loading disabled by Include/Exclude setting.
`

```
17:33:27:695	.OnCurrentFolderItemsChanged(): System.Collections.ObjectModel.ObservableCollection`1[electrifier.Controls.Vanara.ExplorerBrowserItem]
17:33:27:695	.OnCurrentFolderBrowserItemChanged(<'Desktop'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
17:33:27:695	.OnCurrentFolderBrowserItemChanged(<'Desktop'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
17:33:27:695	.NativeTreeViewOnSelectionChanged() Desktop
17:33:27:695	.Navigate(`Desktop`)
17:33:27:695	.ExtractChildItems <Desktop> extracting...
17:33:27:695	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:695	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:695	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:695	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
17:33:27:943	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\System.Security.Permissions.dll'. Symbol loading disabled by Include/Exclude setting.
17:33:28:205	.ExtractChildItems <Desktop> extracted: 65 items.
```

**Comment by dahall** [comment]
I just pushed an update to 4.0.3 (soon available via AppVeyor) that should eliminate the exceptions you're seeing. They weren't problems. I was using exceptions to catch failures when testing for different types of shell items. Let me know if the update works for you.

**Comment by tajbender** [comment]
> I just pushed an update to 4.0.3 (soon available via AppVeyor) that should eliminate the exceptions you're seeing. They weren't problems. I was using exceptions to catch failures when testing for different types of shell items. Let me know if the update works for you.

Thank you very, very much. I'll try that build asap.

**Comment by dahall** [comment]
Did that fix work for you?

**Comment by tajbender** [comment]
> Did that fix work for you?

Yes, it did. 👍 

- Enumeration _**always**_ works now.
- `Libraries` folder is _**always**_ working as well, with proper `DisplayName`.
- As far as I've tested right now, this version is much more optimized in terms of files/sec throughput. 

```
12:39:47:829	.OnCurrentFolderItemsChanged(): System.Collections.ObjectModel.ObservableCollection`1[electrifier.Controls.Vanara.ExplorerBrowserItem]
12:39:47:829	.OnCurrentFolderBrowserItemChanged(<'Desktop'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:39:47:829	.OnCurrentFolderBrowserItemChanged(<'Desktop'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:39:48:066	.NativeTreeViewOnSelectionChanged() Desktop
12:39:48:066	.Navigate(`Desktop`)
12:39:48:066	.ExtractChildItems(<Desktop>) extracting...
12:39:48:066	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:39:48:328	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:39:48:328	.ExtractChildItems(<Desktop>) extracted: 65 items.
12:39:59:316	.NativeTreeViewOnSelectionChanged() This PC
12:39:59:316	.Navigate(`This PC`)
12:39:59:316	.OnCurrentFolderBrowserItemChanged(<'This PC'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:39:59:316	.ExtractChildItems(<This PC>) extracting...
12:39:59:565	.ExtractChildItems(<This PC>) extracted: 4 items.
12:40:01:568	.NativeTreeViewOnSelectionChanged() Recycle Bin
12:40:01:568	.Navigate(`Recycle Bin`)
12:40:01:568	.OnCurrentFolderBrowserItemChanged(<'Recycle Bin'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:40:01:568	.ExtractChildItems(<Recycle Bin>) extracting...
12:40:01:568	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:01:816	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:136	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:382	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:382	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:07:940	The thread '[Thread Destroyed]' (19964) has exited with code 0 (0x0).
12:40:07:940	The thread '[Thread Destroyed]' (11328) has exited with code 0 (0x0).
12:40:08:468	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:971	.ExtractChildItems(<Recycle Bin>) extracted: 221 items.
12:40:12:261	.NativeTreeViewOnSelectionChanged() Control Panel
12:40:12:261	.Navigate(`Control Panel`)
12:40:12:261	.OnCurrentFolderBrowserItemChanged(<'Control Panel'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:40:12:261	.ExtractChildItems(<Control Panel>) extracting...
12:40:12:261	.ExtractChildItems(<Control Panel>) extracted: 9 items.
12:40:16:809	.NativeTreeViewOnSelectionChanged() Libraries
12:40:16:809	.Navigate(`Libraries`)
12:40:16:809	.OnCurrentFolderBrowserItemChanged(<'Libraries'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:40:16:809	.ExtractChildItems(<Libraries>) extracting...
12:40:17:057	.ExtractChildItems(<Libraries>) extracted: 6 items.
12:40:27:631	.NativeTreeViewOnSelectionChanged() Gallery
12:40:27:631	.Navigate(`Gallery`)
12:40:27:631	.OnCurrentFolderBrowserItemChanged(<'Gallery'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:40:27:631	.ExtractChildItems(<Gallery>) extracting...
12:40:28:381	.ExtractChildItems(<Gallery>) extracted: 8395 items.
12:40:35:529	The program '[22756] electrifier.exe' has exited with code 0 (0x0).
```

- `8395 items.` in about 750 ms. (unoptimized, unparallel, without icons) 💨 
- However, as far as I've seen the `IconExtractor` is still broken in some folders.

However, *__Issues__* I have found on my special machine:
- Funny indeed: I have a second `Control Panel` in that enumeration of `Desktop` (the virtual one, not the user profiles Desktop folder).
- My Recycle Bin takes exceptional long to extract:

```
12:40:01:568	.NativeTreeViewOnSelectionChanged() Recycle Bin
12:40:01:568	.Navigate(`Recycle Bin`)
12:40:01:568	.OnCurrentFolderBrowserItemChanged(<'Recycle Bin'>) DependencyObject <'electrifier.Controls.Vanara.ExplorerBrowser'>
12:40:01:568	.ExtractChildItems(<Recycle Bin>) extracting...
12:40:01:568	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:01:816	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:02:065	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:136	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:382	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:05:382	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:07:940	The thread '[Thread Destroyed]' (19964) has exited with code 0 (0x0).
12:40:07:940	The thread '[Thread Destroyed]' (11328) has exited with code 0 (0x0).
12:40:08:468	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:709	Exception thrown: 'System.Runtime.InteropServices.COMException' in Vanara.Windows.Shell.Common.dll
12:40:08:971	.ExtractChildItems(<Recycle Bin>) extracted: 221 items.
```

But I'm still about to investigate these things.

**Comment by tajbender** [comment]
@dahall: this works fine 🆗
